---
title: "Presentation"
author: "Genelle Denzin"
date: "7/31/2019"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

Slides due September 16th
Questions to ask:

- Does interactive mean I should instruct attendees to follow along at R Studio Cloud or is that too much (I could make it optional)
- I use very few slides because I refer to outside the ppt. It doesn't mean the talk will be too short.

## Resources

- https://www.practicereproducibleresearch.org/
- https://www.markdownguide.org/ (what is markdown?)
- https://docs.google.com/document/d/1WvApy4ayQcZaLRpD6bvAqhWncUaPmmRimT016-PrLBk/edit
- https://rmarkdown.rstudio.com/gallery.html
- https://uoftcoders.github.io/rcourse/lec16-rmarkdown.html
- https://youtu.be/s3JldKoA0zw <- use in presentation

## Basic flow of the talk

* give option to follow along at R Studio Cloud, talk about R and R Studio VERY BRIEFLY and how using R Studio Cloud bypasses the need to install that
* forest-level explanation of which part we're thinking about: the data munging between Raw and Visualization. Workflow discussion
* what is markdown
* what is R Markdown
* what is reproducibility
* do not be intimidated by coding b/c you're already doing it
* the role of a versioning tool like git
* a reproducible workflow for our kind (only exploratory data mostly, but still important that everything is correct)

## Tasks

* work on R Studio Cloud- either create something or use/modify someone else's
  - it should be about HMIS data
  - it should use sample data

## The Description NHSDC Has

"How did I create that? Is this accurate? Could someone else recreate this report or visualization and get the same results?" 

Adopting a reproducible data analysis workflow is important for presenting credible and verifiably accurate data results. With free and open source tools, you can regularly create reproducible data analysis that looks amazing and is easily shared. 

R Markdown combines narrative and chunks of code to generate both text and graphical results. Any R Markdown document can refer to any number of data sources and combine them gracefully into one analysis, shareable via HTML, PDF, or Word. 

The basic principles of a reproducible data analysis workflow will be covered, including ways in which the more academic definition of "reproducible research" must be slightly limited for our purposes since we are working with more sensitive data.
